
markdown: kramdown
highlighter: pygments
paginate: nil
permalink: /:title

title: Guobin's Blog
url: http://guobin1112.github.io
feed: /atom.xml
author_info: <a href="http://guobin1112.github.io/">Guobin's Blog</a>

gems: [jekyll-paginate]

